apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  selector:
    app: unifi-controller
  ports:
    - port: 8080
      name: "device-communication"
    - port: 8443
      name: "web-admin"
    - port: 8843
      name: "guest-portal-https"
    - port: 8880
      name: "guest-portal-http"
    - port: 6789
      name: "mobile-throughput-test"
    - port: 5514
      name: "remote-syslog"
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: 'unifi-controller'
spec:
  selector:
    app: unifi-controller
  ports:
    - port: 3478
      protocol: UDP
      name: "stun"
    - port: 10001
      protocol: UDP
      name: "ap-discovery"
    - port: 1900
      protocol: UDP
      name: "discoverable-l2"
  type: LoadBalancer
